### ISSUE TITLE
stornierte Zahlungen werden als "nicht bezahlt" im Ticket-Shop geführt

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#2]
btw eine Order Number wäre hilfreich um die Buchungen eindeutig bzw. einfacher referenzierten zu können...

Order
time: 12.04.2023, 14:28
Sum: 63,78 €
state: "nicht bezahlt"
customer: Thomas Rauch

Ein Blick im Stripe lässt vermuten, das diese Zahlung storniert wurde. Wie es scheint werden Zahlungen nach einem Storno anonymiisert, so das diese nicht mehr für den Endnutzer (wie mich) eindeutig zuordbar sind. Eine Aktualisierung über den Button "erneut prüfen" ändert den Status nicht

Zielverhalten:
Buchung sollte im Status "storniert" gehen

**Comment by hrueger** [comment]
Hi, das ist tatsächlich mehr ein Feature als ein Bug. Der Kunde hat hier auf "Kaufen" geklickt, dann aber bei Stripe keine Zahlungsdaten eingegeben. Der Grund, dass die Bestellung nicht bei uns storniert wird, ist, dass dann die Plätze direkt wieder frei verfügbar wären. Stattdessen kann man hier dem Kunden eine "Zahlungserinnerung" per Mail schicken (die enthält einen Link, mit dem man die Bestellung abschließen kann) oder die Bestellung im Ticket-Shop stornieren.

In Zukunft wird das automatisch(er) passieren, aber ich bin noch nicht so weit gekommen (ich arbeite grad eh immer bis 3 Uhr nachts... :-| )

Ist der Issue damit gelöst? Diese Bestellung kannst Du stornieren, er hat ja direkt danach nochmal gekauft, die gleichen Karten und da hats funktioniert.

**Comment by derLausitzer** [comment]
für mich wäre das dann gelöst, für den Shop noch nicht :-) der Job zum Aufräumen wäre schon gut
