### ISSUE TITLE
PaymentIntent-Status: requires_action -> storno

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#3]
Order:
pi_3Mzkc3HFA5nKfZkr1erRdljJ

die Order ist im Status canceled

am 22.04. gab es den Status requires_action
am 23.04. wurde die Order dann storniert

ich würde die Kundin gerne anschreiben, würde dazu aber erst einmal verstehen wollen was hier eigentlich passiert ist. Kannst Du das erklären? 
Danke!

**Comment by hrueger** [comment]
Duplicate of #2 

Ich schließ das, ist genau das gleiche wie bei #2
