### ISSUE TITLE
stornierte Buchungen belegen Plätze

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#4]
hängt mit #2 zusammen

- Zahlungen im Ticket-Status "nicht bezahlt" und im Stripe-Status "storniert" werden als verkaufte Tickets geführt

Zielverhalten:
Tickets sind im Status storniert oder canceled, die Karten sind storniert, Plätze werden nicht als verkauft gezählt

**Comment by hrueger** [comment]
Ist genau das gleiche wie #2, Du musst die Bestellung stornieren, dann sind die Plätze wieder frei.
Das ist ein Feature, um die Leute doch im Nachhinein noch zum Kauf zu bewegen bzw. den Service zu bieten, dass die Plätze nicht weg sind, wenn jemand das Bezahlfenster geschlossen hat.

**Comment by hrueger** [comment]
Closing as duplicate of #2
