### ISSUE TITLE
Feature Request: langlaufende Zahlungsmethoden mit Offset einrichten 

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#5]
Zahlungsmethoden, wie SEPA-Zahlung sollten x Tage vor Ende der VVK nicht mehr angeboten werden, da ungewiss ist, ob die Zahlung ausgeführt werden kann und der Kunde dann auch keine Karte mehr erhält

PS: geht vielleicht auch schon über Stripe zu steuern? konnte erst einmal nichts dazu finden

**Comment by hrueger** [comment]
Das ist schon implementiert. Ab 7 Tage vor Veranstaltungsbeginn verschwinden SEPA und SOFORT automatisch. Karte und Girpay sind ja in Echtzeit, die bleiben verfügbar.

**Comment by derLausitzer** [comment]
wunderbar, hatte ich gestern bei der Bestellung auch schon so festgestellt
