### ISSUE TITLE
Prio1: Abbruch mit 500 bei Bestellung von ermäßigten Ticket mit 50%

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#6]
Zwei Ticket liegen im WK ein volles Ticket, ein Ticket mit 50% Ermäßigung 
bei "zur Kasse" kommt

`500 
Invalid integer: 797.5
`

der Bestellprozess kann nicht fortgeführt werden. Workaround:

die Ermäßigung wird heraus genommen, die Bezahlung wäre möglich

Vermutung: halbe Tickets gingen vermutlich noch nie!!

Zielzustand: Tickets mit Ermäßigung können gebucht werden

**Comment by hrueger** [comment]
Update mit Fix ist hochgeladen, sollte jetzt gehen 👍

**Comment by derLausitzer** [comment]
Nachtest erfolgreich (Preis wieder auf ungerade gesetzt)
