### ISSUE TITLE
nth: zusätzliche Auswahlfelder lassen sich nicht wieder löschen

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#7]
sind zusätzliche Auswahlfelder (Sonstiges) einmal angelegt lassen diese sich nicht wieder löschen. Dies geht nur indirekt, wenn das zusätzliche Feld komplett gelöscht wird. Dann müssen allerdings alle Auswahlfelder wieder neu angelegt werden.

Wäre nice to have.

**Comment by hrueger** [comment]
Guter Punkt, kommt morgen. Danke für den Hinweis

**Comment by hrueger** [comment]
Ist behoben 👍 gibt einen Mülleimer Button.

**Comment by derLausitzer** [comment]
löschen geht nun!

**Comment by derLausitzer** [comment]
die gelöschte Option "allg." von der Auswahlliste "Name des Schülers" ist wieder da und lässt sich nun auch nicht mehr löschen, obwohl eine Bestätigung der Änderung nach dem speichern kommt. Es wurde das "kleine" und das "große" speichern getestet.

**Comment by hrueger** [comment]
Huh? Sehr komisch, kann ich nicht reproduzieren. Wie ist es wieder aufgetaucht? Von selbst?
Ich konnte die grad löschen und jetzt ist sie weg. Ich bekomm sie auch nicht wieder.

Das "große" Speichern oben ist für die Checkbox "Diese Organisation wird auf der Startseite öffentlich gelistet.", das "kleine" Speichern ist also das relevante.
