### ISSUE TITLE
Freikarten werden mit Safari unter MacOS doppelt erstellt

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#8]
habe gerade einen Sack voller Freikarten erstellt. musste nun feststellen das diese zwei mal ausgegeben werden (es liegen zwei PDF dann auf der Platte)

dachte erst, na vielleicht war die Einstellung auf 2 Karten drucken, habe daher eben noch mal eine Freikarte auf Deinen Namen erstellt, explizit mir der Einstellung Anzahl=1

Anbei nun Deine "beiden" Freikarten

[one-per-page-5.pdf](https://github.com/Dein-Ticket-Shop/help/files/11367254/one-per-page-5.pdf)

[one-per-page-4.pdf](https://github.com/Dein-Ticket-Shop/help/files/11367255/one-per-page-4.pdf)

Hatte mich auch schon beim Counter des Dateinamens gewundert...Plätze scheinen aber nicht doppelt vergeben worden zu sein (hätte ich allerdings gerne noch mal bestätigt)

btw: der Dateiname könnte den Namen `<Verantaltung-Freikarte-counter>` haben, wäre ebenfalls nth

**Comment by hrueger** [comment]
Soweit ich das am Handy sehe, ist das dieselbe Karte (gleiche ID links am Barcode). Dann sind die Plätze garantiert nicht 2x weg.
Vllt. lädt es es nur 2x runter? Welchen Browser und welches Betriebssystem nutzt Du?

**Comment by derLausitzer** [comment]
So sieht es wohl aus. Es gehen immer zwei Fenster auf. PopUps sind erlaubt. MacOS 13.3.1 mit Safari 16.4

**Comment by hrueger** [comment]
bäh ;-) Soweit ich weiß, unterstützt Safari das direkte PDF drucken nicht... Ich muss mir da was überlegen, hab aber keinen Mac, mit dem ich das testen könnte.
Apple ist so nervig, jeder dritte Fehler ist nur, weil Apple irgendwas Standard-konform baut... :-|

**Comment by hrueger** [comment]
Könntest Du mal Chrome probieren?

**Comment by derLausitzer** [comment]
ja das ist echt gruselig, gerade mit Chrome getestet, hier geht ein ordentliches Drucken Menü auf.. noch in Ergänzung zu dem Verhalten bei Safari, hab dazu auch mal den Screen angehangen

![Bild 02 05 23 um 09 26](https://user-images.githubusercontent.com/131981887/235605342-e25f33cf-6b44-4489-9905-dc26ea3d0c89.jpg)

folgender Ablauf (gruselig)
Aktion "Drucken"-> es öffnet ein neues Browserfenster und die Meldung "Popups erlauben" wie auf dem Screen zu sehen. -> neues Fenster "blank" schließen-> FM schließen-> es öffnet sich ein neuer Browsertab und das (bzw die beiden) PDF werden unter downloads gespeichert.

PopUps sind in den Einstellungen wie folgt erlaubt:

![Bild 02 05 23 um 09 31](https://user-images.githubusercontent.com/131981887/235606175-9c140ffe-7212-4185-b8d5-f1d1a3527077.jpg)

 
wegen mir musst Du für das Ticket jetzt keine Kopfstände machen, leg das Ding auf Halde, der Workaround Chrome tut ja

**Comment by hrueger** [comment]
> wegen mir musst Du für das Ticket jetzt keine Kopfstände machen, leg das Ding auf Halde, der Workaround Chrome tut ja
ok, danke!
