### ISSUE TITLE
Auffinden bestimmter Freikarten umständlich

### ISSUE THREAD

**Issue by derLausitzer** [Dein-Ticket-Shop/help#9]
nachdem ich nun die ganzen Freikarten generiert und versandt habe, würde ich gerne die Freikarten wieder stornieren wollen, die eine negative Rückmeldung gegeben haben (um die Plätze wieder frei zu bekommen). Leider gibt es keine Suche (oder doch?) und in der Bestellübersicht lässt sich es auch nicht sehen...wie schon einem anderen Ticket am Rande erwähnt, wäre wahrscheinlich eine eindeutige Order-ID hilfreich. Wenn diese auf der Karte wäre, könnte man in einer potentiellen Suche danach suchen oder zumindest in der Bestellübersicht in einer Spalte mit ausgeben und darüber dann finden. 

Ein weiterer Anwendungsfall wäre der erneute Druck/Versand einer bestimmten Freikarte.

Any Ideas für einen quick hack?

**Comment by hrueger** [comment]
Ist behoben 👍 Hab eine Suche eingebaut. Die sucht auch nach den Notizen bei Freikarten. Hilft Dir das?

Re: Order ID: Schaff ich aktuell einfach zeitlich nicht. Bei uns läuft grad der Jazzfrühling, ein Festival mit 53 Konzerten, ich bin für alle Abendkassen zuständig und mach noch Licht bei 5 Konzerten ;-)

**Comment by hrueger** [comment]
Order ID steht aber auf meiner internen Liste.

**Comment by derLausitzer** [comment]
Suche erfüllt den Zweck!
